services:
  vid2cat:
    image: guohuiyuan/vid2cat:latest
    container_name: vid2cat
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
